### PR TITLE
Navbar, list.html, and visual extensions

### PR DESCRIPTION
**Pull request by 0xBlue2**
A full explanation is here - [https://github.com/dancingbear344/hugo-theme-shell](https://github.com/dancingbear344/hugo-theme-shell)

It adds features for a navbar at the bottom, a `list.html` page to list pages, and the ability to list extensions after single pages to distinguish them from directories.

The navbar and extensions are completely optional:
(in `config.toml`)
```
[Params.Navbar]
  use = true # false if you don't want it
  
[Params.Extensions]
  use = true # false if you don't want it
  ext = ".txt" # extension to add after single page
```

Currently, the only way to remove the listing ability is to delete `list.html` or make it blank, but doing so doesn't break anything, so if people don't want it, it's easy to remove.

### CODE REVIEW

**Comment by 0xBlue2** [comment]
Theres a `CHANGES` file in the pull request that shows what code I added and where I added it too.

**Comment by Yukuro** [comment]
Thanks for the PR !
This navbar is very cool.

I am going to merge this PR.
However, I may change the appearance of some of them to organize the files.
So be aware that the look may not be as you PR.

**Comment by 0xBlue2** [comment]
Thanks! Change it as you like!

**Comment by 0xBlue2** [comment]
I forgot to update this, I used the wrong comments for ```baseof.html``` so "# Additions start/stop here" shows up as actual text instead of being just a comment 

[https://github.com/Yukuro/hugo-theme-shell/blob/0528c569a72c95558ca5df2d09a5c4f88e380aff/layouts/_default/baseof.html#L11](https://github.com/Yukuro/hugo-theme-shell/blob/0528c569a72c95558ca5df2d09a5c4f88e380aff/layouts/_default/baseof.html#L11)

**Pull request merged**
